# 自动归档脚本手动测试

虽然大部分代码已经被单元测试覆盖到了，但是主要的main函数以及部分函数可能仍然未覆盖到，
且由于集成测试编写难度过大，暂且写不出来。
所以当代码有大量改动时，建议手动在此仓库的Issue中对归档流水线进行测试

## 测试用例
> [!WARNING]
> 由于Github和Gitlab两个平台的接口存在差异
> 所以归档脚本实现方式不一致
> 若有时间，最好是Github和Gitlab两侧流水线都进行手动测试

> [!NOTE]
> 在测试前，要确认对应的issue单号是否已经写入`修改归档.md`了,
> 如果某个issue满足归档条件时被close且已经归档过了，归档流水线会留下类似评论：
> `外部Issue#xxx 已存在归档记录，无需再次归档，跳过归档流程`


以下为issue内容信息表格，建议从上往下逐一添加或者移除某些内容，手动关闭issue并观察归档流水线的行为是否符合预期：
|               描述                |                    标签                     |        评论        |                        关闭issue预期效果                        |
| :-------------------------------: | :-----------------------------------------: | :----------------: | :-------------------------------------------------------------: |
|                无                 |                     无                      |         无         |                归档流水线无视此状态，issue被关闭                |
| 包含“【发现版本号】：0.99.954b9 ” |                     无                      |         无         |                归档流水线无视此状态，issue被关闭                |
| 包含“【发现版本号】：0.99.954b9 ” |                    “bug”                    |         无         |                归档流水线无视此状态，issue被关闭                |
| 包含“【发现版本号】：0.99.954b9 ” |                     无                      | “0.99.955测试通过” |                归档流水线无视此状态，issue被关闭                |
| 包含“【发现版本号】：0.99.954b9 ” |              “resolved 已解决”              |         无         |         issue被重新打开，并评论“找不到归档版本号关键字”         |
| 包含“【发现版本号】：0.99.954b9 ” |              “resolved 已解决”              | “0.99.955测试通过” |          issue被重新打开，并评论“找不到Issue类型标签”           |
|                无                 |          “resolved 已解决”，“bug”           | “0.99.955测试通过” |            issue被重新打开，并评论“找不到引入版本号”            |
| 包含“【发现版本号】：0.99.954b9 ” |                    “bug”                    | “0.99.955测试通过” |           issue被重新打开，并评论“找不到归档所需标签”           |
|                无                 | “resolved 已解决”，“enhancement 优化或建议” | “0.99.955测试通过” | issue被正常关闭且被正确归档，并评论“外部Issue#XXX 自动归档成功” |
| 包含“【发现版本号】：0.99.954b9 ” |          “resolved 已解决”，“bug”           | “0.99.955测试通过” | issue被正常关闭且被正确归档，并评论“外部Issue#XXX 自动归档成功” |
